### ISSUE TITLE
[ Enhancement ] File Structure and Code Refactoring / Formatting

### ISSUE THREAD

**Issue by nub-rin** [clubgamma/Sudoku#16]
Hello!
I was thinking to help in managing the file structure and refactoring of the code.

# Benefits
- This will greatly benefit in any future collaborations and QoL for the developers who will be potentially work on this project.
- Easier to manage the codebase.

I can show you some examples of how it will work out if you want.

Happy Hacking!!

**Comment by soni-shashan** [comment]
want to work on it? @nub-rin

**Comment by nub-rin** [comment]
> want to work on it? @nub-rin 

Sure

**Comment by Meetpidev** [comment]
@soni-shashan  is it still not solved ? if not then can you assign to me this task ??

**Comment by soni-shashan** [comment]
any updates..? @nub-rin

**Comment by nub-rin** [comment]
@soni-shashan Sill working on it, some things came up. Meanwhile if @Meetpidev want's to work on this they can. I can give you an estimate till when I can submit a PR resolving this issue which is anytime before tomorrow 6 pm IST.

**Comment by nandit27** [comment]
@soni-shashan my recent solves both the current issues.
