### ISSUE TITLE
Building a GUI-Based Sudoku Solver in C with GTK

### ISSUE THREAD

**Issue by soni-shashan** [clubgamma/Sudoku#2]
### To create a GUI-based Sudoku solver in C, use the GTK library. First, write your Sudoku-solving logic in C using a backtracking algorithm. Then, create the GUI by initializing a GTK application and designing a 9x9 grid of text entry widgets to represent the Sudoku board. Add a "Solve" button that triggers the solver function to update the grid with the solution. Use GTK's layout management to arrange the grid and button, and update the values in the entries after solving the puzzle. This structure provides an interactive Sudoku solver with a graphical interface.

**Comment by nandit27** [comment]
@soni-shashan can u please assign this to me ?

**Comment by soni-shashan** [comment]
@nandit27 any update?

**Comment by nandit27** [comment]
@soni-shashan more than half of the work is done. Only some errors need to be resolved.
