### ISSUE TITLE
Automatic Grid Size Detection and Validation from File Input

### ISSUE THREAD

**Issue by soni-shashan** [clubgamma/Sudoku#21]
### Currently, our project does not work when reading a grid from a file because the initial grid size is set to 0. We need to automatically determine the grid size from the file input. If the grid size is valid, the program should proceed to solve it.

**Comment by Meetpidev** [comment]
@soni-shashan 

### MY APPROCH
- Fristly we have to read lines from the file to count how many rows and columns there are. This helps determine the grid size automatically.
- After counting, then we check if the detected size is valid before proceeding.
- we reset the file pointer to read the Sudoku grid correctly.
- If invalid sizes or characters are found, the program outputs appropriate error messages.....
